// Code generated by entc, DO NOT EDIT.

package adamaorder

const (
	// Label holds the string label denoting the adamaorder type in the database.
	Label = "adama_order"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldOrderID holds the string denoting the order_id field in the database.
	FieldOrderID = "order_id"
	// FieldGoodsID holds the string denoting the goods_id field in the database.
	FieldGoodsID = "goods_id"
	// Table holds the table name of the adamaorder in the database.
	Table = "adama_orders"
)

// Columns holds all SQL columns for adamaorder fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldOrderID,
	FieldGoodsID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
