// Code generated by entc, DO NOT EDIT.

package adamagoods

const (
	// Label holds the string label denoting the adamagoods type in the database.
	Label = "adama_goods"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGoodsID holds the string denoting the goods_id field in the database.
	FieldGoodsID = "goods_id"
	// FieldAdamaPrice holds the string denoting the adama_price field in the database.
	FieldAdamaPrice = "adama_price"
	// FieldStockCount holds the string denoting the stock_count field in the database.
	FieldStockCount = "stock_count"
	// FieldStartDate holds the string denoting the start_date field in the database.
	FieldStartDate = "start_date"
	// FieldEndDate holds the string denoting the end_date field in the database.
	FieldEndDate = "end_date"
	// Table holds the table name of the adamagoods in the database.
	Table = "adama_goods"
)

// Columns holds all SQL columns for adamagoods fields.
var Columns = []string{
	FieldID,
	FieldGoodsID,
	FieldAdamaPrice,
	FieldStockCount,
	FieldStartDate,
	FieldEndDate,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
