// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// OrdersColumns holds the columns for the "orders" table.
	OrdersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "sn", Type: field.TypeString},
		{Name: "gid", Type: field.TypeInt64},
		{Name: "uid", Type: field.TypeInt64},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
	}
	// OrdersTable holds the schema information for the "orders" table.
	OrdersTable = &schema.Table{
		Name:        "orders",
		Columns:     OrdersColumns,
		PrimaryKey:  []*schema.Column{OrdersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// AdamaGoodsColumns holds the columns for the "adama_goods" table.
	AdamaGoodsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "goods_id", Type: field.TypeInt64},
		{Name: "adama_price", Type: field.TypeFloat64, SchemaType: map[string]string{"mysql": "decimal(10,2)"}},
		{Name: "stock_count", Type: field.TypeInt64},
		{Name: "start_date", Type: field.TypeTime},
		{Name: "end_date", Type: field.TypeTime},
	}
	// AdamaGoodsTable holds the schema information for the "adama_goods" table.
	AdamaGoodsTable = &schema.Table{
		Name:        "adama_goods",
		Columns:     AdamaGoodsColumns,
		PrimaryKey:  []*schema.Column{AdamaGoodsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// AdamaOrdersColumns holds the columns for the "adama_orders" table.
	AdamaOrdersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "order_id", Type: field.TypeInt64},
		{Name: "goods_id", Type: field.TypeInt64},
	}
	// AdamaOrdersTable holds the schema information for the "adama_orders" table.
	AdamaOrdersTable = &schema.Table{
		Name:        "adama_orders",
		Columns:     AdamaOrdersColumns,
		PrimaryKey:  []*schema.Column{AdamaOrdersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		OrdersTable,
		AdamaGoodsTable,
		AdamaOrdersTable,
	}
)

func init() {
}
