// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.0.0

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type OrderHTTPServer interface {
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderReply, error)
	CreateAdamaOrder(context.Context, *CreateAdamaOrderRequest) (*CreateAdamaOrderReply, error)
	CreateAdamaOrderCancel(context.Context, *CreateAdamaOrderRequest) (*CreateAdamaOrderReply, error)
	CreateAdamaOrderConfirm(context.Context, *CreateAdamaOrderRequest) (*CreateAdamaOrderReply, error)
	CreateAdamaOrderTry(context.Context, *CreateAdamaOrderRequest) (*CreateAdamaOrderReply, error)
}

func RegisterOrderHTTPServer(s *http.Server, srv OrderHTTPServer) {
	r := s.Route("/")
	r.POST("/order", _Order_CreateOrder0_HTTP_Handler(srv))
	r.POST("/adama/order", _Order_CreateAdamaOrder0_HTTP_Handler(srv))
	r.POST("/adama/orderTry", _Order_CreateAdamaOrderTry0_HTTP_Handler(srv))
	r.POST("/adama/orderConfirm", _Order_CreateAdamaOrderConfirm0_HTTP_Handler(srv))
	r.POST("/adama/orderCancel", _Order_CreateAdamaOrderCancel0_HTTP_Handler(srv))
}

func _Order_CreateOrder0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.order.service.v1.Order/CreateOrder")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateOrder(ctx, req.(*CreateOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateOrderReply)
		return ctx.Result(200, reply)
	}
}

func _Order_CreateAdamaOrder0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateAdamaOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.order.service.v1.Order/CreateAdamaOrder")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateAdamaOrder(ctx, req.(*CreateAdamaOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateAdamaOrderReply)
		return ctx.Result(200, reply)
	}
}

func _Order_CreateAdamaOrderTry0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateAdamaOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.order.service.v1.Order/CreateAdamaOrderTry")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateAdamaOrderTry(ctx, req.(*CreateAdamaOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateAdamaOrderReply)
		return ctx.Result(200, reply)
	}
}

func _Order_CreateAdamaOrderConfirm0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateAdamaOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.order.service.v1.Order/CreateAdamaOrderConfirm")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateAdamaOrderConfirm(ctx, req.(*CreateAdamaOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateAdamaOrderReply)
		return ctx.Result(200, reply)
	}
}

func _Order_CreateAdamaOrderCancel0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateAdamaOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.order.service.v1.Order/CreateAdamaOrderCancel")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateAdamaOrderCancel(ctx, req.(*CreateAdamaOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateAdamaOrderReply)
		return ctx.Result(200, reply)
	}
}

type OrderHTTPClient interface {
	CreateOrder(ctx context.Context, req *CreateOrderRequest, opts ...http.CallOption) (rsp *CreateOrderReply, err error)
	CreateAdamaOrder(ctx context.Context, req *CreateAdamaOrderRequest, opts ...http.CallOption) (rsp *CreateAdamaOrderReply, err error)
	CreateAdamaOrderCancel(ctx context.Context, req *CreateAdamaOrderRequest, opts ...http.CallOption) (rsp *CreateAdamaOrderReply, err error)
	CreateAdamaOrderConfirm(ctx context.Context, req *CreateAdamaOrderRequest, opts ...http.CallOption) (rsp *CreateAdamaOrderReply, err error)
	CreateAdamaOrderTry(ctx context.Context, req *CreateAdamaOrderRequest, opts ...http.CallOption) (rsp *CreateAdamaOrderReply, err error)
}

type OrderHTTPClientImpl struct {
	cc *http.Client
}

func NewOrderHTTPClient(client *http.Client) OrderHTTPClient {
	return &OrderHTTPClientImpl{client}
}

func (c *OrderHTTPClientImpl) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...http.CallOption) (*CreateOrderReply, error) {
	var out CreateOrderReply
	pattern := "/order"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/api.order.service.v1.Order/CreateOrder"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *OrderHTTPClientImpl) CreateAdamaOrder(ctx context.Context, in *CreateAdamaOrderRequest, opts ...http.CallOption) (*CreateAdamaOrderReply, error) {
	var out CreateAdamaOrderReply
	pattern := "/adama/order"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/api.order.service.v1.Order/CreateAdamaOrder"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *OrderHTTPClientImpl) CreateAdamaOrderCancel(ctx context.Context, in *CreateAdamaOrderRequest, opts ...http.CallOption) (*CreateAdamaOrderReply, error) {
	var out CreateAdamaOrderReply
	pattern := "/adama/orderCancel"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/api.order.service.v1.Order/CreateAdamaOrderCancel"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *OrderHTTPClientImpl) CreateAdamaOrderConfirm(ctx context.Context, in *CreateAdamaOrderRequest, opts ...http.CallOption) (*CreateAdamaOrderReply, error) {
	var out CreateAdamaOrderReply
	pattern := "/adama/orderConfirm"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/api.order.service.v1.Order/CreateAdamaOrderConfirm"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *OrderHTTPClientImpl) CreateAdamaOrderTry(ctx context.Context, in *CreateAdamaOrderRequest, opts ...http.CallOption) (*CreateAdamaOrderReply, error) {
	var out CreateAdamaOrderReply
	pattern := "/adama/orderTry"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/api.order.service.v1.Order/CreateAdamaOrderTry"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
