// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// AdamaGoods is the predicate function for adamagoods builders.
type AdamaGoods func(*sql.Selector)

// AdamaOrder is the predicate function for adamaorder builders.
type AdamaOrder func(*sql.Selector)
