// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/littleSand/adama/app/job/service/internal/biz"
	"github.com/littleSand/adama/app/job/service/internal/conf"
	"github.com/littleSand/adama/app/job/service/internal/data"
	"github.com/littleSand/adama/app/job/service/internal/server"
	"github.com/littleSand/adama/app/job/service/internal/service"
	"github.com/littleSand/adama/app/job/service/job"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData, logger)
	dataData, cleanup, err := data.NewData(confData, db, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	orderQueueRepo := data.NewOrderRepo(dataData, logger)
	orderQueueUsecase := biz.NewOrderQueueUsecase(orderQueueRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase, orderQueueUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, logger)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	orderService := service.NewOrderService(orderQueueUsecase)
	jobServer := job.NewJOBServer(confServer, confData, orderService, logger)
	app := newApp(logger, httpServer, grpcServer, jobServer)
	return app, func() {
		cleanup()
	}, nil
}
