// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/littleSand/adama/app/order/service/internal/data/ent/adamaorder"
)

// AdamaOrderCreate is the builder for creating a AdamaOrder entity.
type AdamaOrderCreate struct {
	config
	mutation *AdamaOrderMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (soc *AdamaOrderCreate) SetUserID(i int64) *AdamaOrderCreate {
	soc.mutation.SetUserID(i)
	return soc
}

// SetOrderID sets the "order_id" field.
func (soc *AdamaOrderCreate) SetOrderID(i int64) *AdamaOrderCreate {
	soc.mutation.SetOrderID(i)
	return soc
}

// SetGoodsID sets the "goods_id" field.
func (soc *AdamaOrderCreate) SetGoodsID(i int64) *AdamaOrderCreate {
	soc.mutation.SetGoodsID(i)
	return soc
}

// SetID sets the "id" field.
func (soc *AdamaOrderCreate) SetID(i int64) *AdamaOrderCreate {
	soc.mutation.SetID(i)
	return soc
}

// Mutation returns the AdamaOrderMutation object of the builder.
func (soc *AdamaOrderCreate) Mutation() *AdamaOrderMutation {
	return soc.mutation
}

// Save creates the AdamaOrder in the database.
func (soc *AdamaOrderCreate) Save(ctx context.Context) (*AdamaOrder, error) {
	var (
		err  error
		node *AdamaOrder
	)
	if len(soc.hooks) == 0 {
		if err = soc.check(); err != nil {
			return nil, err
		}
		node, err = soc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AdamaOrderMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = soc.check(); err != nil {
				return nil, err
			}
			soc.mutation = mutation
			node, err = soc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(soc.hooks) - 1; i >= 0; i-- {
			mut = soc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, soc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (soc *AdamaOrderCreate) SaveX(ctx context.Context) *AdamaOrder {
	v, err := soc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// check runs all checks and user-defined validators on the builder.
func (soc *AdamaOrderCreate) check() error {
	if _, ok := soc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New("ent: missing required field \"user_id\"")}
	}
	if _, ok := soc.mutation.OrderID(); !ok {
		return &ValidationError{Name: "order_id", err: errors.New("ent: missing required field \"order_id\"")}
	}
	if _, ok := soc.mutation.GoodsID(); !ok {
		return &ValidationError{Name: "goods_id", err: errors.New("ent: missing required field \"goods_id\"")}
	}
	return nil
}

func (soc *AdamaOrderCreate) sqlSave(ctx context.Context) (*AdamaOrder, error) {
	_node, _spec := soc.createSpec()
	if err := sqlgraph.CreateNode(ctx, soc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	if _node.ID == 0 {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	return _node, nil
}

func (soc *AdamaOrderCreate) createSpec() (*AdamaOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &AdamaOrder{config: soc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: adamaorder.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: adamaorder.FieldID,
			},
		}
	)
	if id, ok := soc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := soc.mutation.UserID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: adamaorder.FieldUserID,
		})
		_node.UserID = value
	}
	if value, ok := soc.mutation.OrderID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: adamaorder.FieldOrderID,
		})
		_node.OrderID = value
	}
	if value, ok := soc.mutation.GoodsID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: adamaorder.FieldGoodsID,
		})
		_node.GoodsID = value
	}
	return _node, _spec
}

// AdamaOrderCreateBulk is the builder for creating many AdamaOrder entities in bulk.
type AdamaOrderCreateBulk struct {
	config
	builders []*AdamaOrderCreate
}

// Save creates the AdamaOrder entities in the database.
func (socb *AdamaOrderCreateBulk) Save(ctx context.Context) ([]*AdamaOrder, error) {
	specs := make([]*sqlgraph.CreateSpec, len(socb.builders))
	nodes := make([]*AdamaOrder, len(socb.builders))
	mutators := make([]Mutator, len(socb.builders))
	for i := range socb.builders {
		func(i int, root context.Context) {
			builder := socb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AdamaOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, socb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, socb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				if nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, socb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (socb *AdamaOrderCreateBulk) SaveX(ctx context.Context) []*AdamaOrder {
	v, err := socb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
