// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/littleSand/adama/app/order/service/internal/data/ent/adamagoods"
	"github.com/littleSand/adama/app/order/service/internal/data/ent/predicate"
)

// AdamaGoodsUpdate is the builder for updating AdamaGoods entities.
type AdamaGoodsUpdate struct {
	config
	hooks    []Hook
	mutation *AdamaGoodsMutation
}

// Where adds a new predicate for the AdamaGoodsUpdate builder.
func (sgu *AdamaGoodsUpdate) Where(ps ...predicate.AdamaGoods) *AdamaGoodsUpdate {
	sgu.mutation.predicates = append(sgu.mutation.predicates, ps...)
	return sgu
}

// SetGoodsID sets the "goods_id" field.
func (sgu *AdamaGoodsUpdate) SetGoodsID(i int64) *AdamaGoodsUpdate {
	sgu.mutation.ResetGoodsID()
	sgu.mutation.SetGoodsID(i)
	return sgu
}

// AddGoodsID adds i to the "goods_id" field.
func (sgu *AdamaGoodsUpdate) AddGoodsID(i int64) *AdamaGoodsUpdate {
	sgu.mutation.AddGoodsID(i)
	return sgu
}

// SetAdamaPrice sets the "adama_price" field.
func (sgu *AdamaGoodsUpdate) SetAdamaPrice(f float64) *AdamaGoodsUpdate {
	sgu.mutation.ResetAdamaPrice()
	sgu.mutation.SetAdamaPrice(f)
	return sgu
}

// AddAdamaPrice adds f to the "adama_price" field.
func (sgu *AdamaGoodsUpdate) AddAdamaPrice(f float64) *AdamaGoodsUpdate {
	sgu.mutation.AddAdamaPrice(f)
	return sgu
}

// SetStockCount sets the "stock_count" field.
func (sgu *AdamaGoodsUpdate) SetStockCount(i int64) *AdamaGoodsUpdate {
	sgu.mutation.ResetStockCount()
	sgu.mutation.SetStockCount(i)
	return sgu
}

// AddStockCount adds i to the "stock_count" field.
func (sgu *AdamaGoodsUpdate) AddStockCount(i int64) *AdamaGoodsUpdate {
	sgu.mutation.AddStockCount(i)
	return sgu
}

// SetStartDate sets the "start_date" field.
func (sgu *AdamaGoodsUpdate) SetStartDate(t time.Time) *AdamaGoodsUpdate {
	sgu.mutation.SetStartDate(t)
	return sgu
}

// SetEndDate sets the "end_date" field.
func (sgu *AdamaGoodsUpdate) SetEndDate(t time.Time) *AdamaGoodsUpdate {
	sgu.mutation.SetEndDate(t)
	return sgu
}

// Mutation returns the AdamaGoodsMutation object of the builder.
func (sgu *AdamaGoodsUpdate) Mutation() *AdamaGoodsMutation {
	return sgu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (sgu *AdamaGoodsUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(sgu.hooks) == 0 {
		affected, err = sgu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AdamaGoodsMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sgu.mutation = mutation
			affected, err = sgu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(sgu.hooks) - 1; i >= 0; i-- {
			mut = sgu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sgu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (sgu *AdamaGoodsUpdate) SaveX(ctx context.Context) int {
	affected, err := sgu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (sgu *AdamaGoodsUpdate) Exec(ctx context.Context) error {
	_, err := sgu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sgu *AdamaGoodsUpdate) ExecX(ctx context.Context) {
	if err := sgu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (sgu *AdamaGoodsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   adamagoods.Table,
			Columns: adamagoods.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: adamagoods.FieldID,
			},
		},
	}
	if ps := sgu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := sgu.mutation.GoodsID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: adamagoods.FieldGoodsID,
		})
	}
	if value, ok := sgu.mutation.AddedGoodsID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: adamagoods.FieldGoodsID,
		})
	}
	if value, ok := sgu.mutation.AdamaPrice(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: adamagoods.FieldAdamaPrice,
		})
	}
	if value, ok := sgu.mutation.AddedAdamaPrice(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: adamagoods.FieldAdamaPrice,
		})
	}
	if value, ok := sgu.mutation.StockCount(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: adamagoods.FieldStockCount,
		})
	}
	if value, ok := sgu.mutation.AddedStockCount(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: adamagoods.FieldStockCount,
		})
	}
	if value, ok := sgu.mutation.StartDate(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: adamagoods.FieldStartDate,
		})
	}
	if value, ok := sgu.mutation.EndDate(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: adamagoods.FieldEndDate,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, sgu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adamagoods.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// AdamaGoodsUpdateOne is the builder for updating a single AdamaGoods entity.
type AdamaGoodsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AdamaGoodsMutation
}

// SetGoodsID sets the "goods_id" field.
func (sguo *AdamaGoodsUpdateOne) SetGoodsID(i int64) *AdamaGoodsUpdateOne {
	sguo.mutation.ResetGoodsID()
	sguo.mutation.SetGoodsID(i)
	return sguo
}

// AddGoodsID adds i to the "goods_id" field.
func (sguo *AdamaGoodsUpdateOne) AddGoodsID(i int64) *AdamaGoodsUpdateOne {
	sguo.mutation.AddGoodsID(i)
	return sguo
}

// SetAdamaPrice sets the "adama_price" field.
func (sguo *AdamaGoodsUpdateOne) SetAdamaPrice(f float64) *AdamaGoodsUpdateOne {
	sguo.mutation.ResetAdamaPrice()
	sguo.mutation.SetAdamaPrice(f)
	return sguo
}

// AddAdamaPrice adds f to the "adama_price" field.
func (sguo *AdamaGoodsUpdateOne) AddAdamaPrice(f float64) *AdamaGoodsUpdateOne {
	sguo.mutation.AddAdamaPrice(f)
	return sguo
}

// SetStockCount sets the "stock_count" field.
func (sguo *AdamaGoodsUpdateOne) SetStockCount(i int64) *AdamaGoodsUpdateOne {
	sguo.mutation.ResetStockCount()
	sguo.mutation.SetStockCount(i)
	return sguo
}

// AddStockCount adds i to the "stock_count" field.
func (sguo *AdamaGoodsUpdateOne) AddStockCount(i int64) *AdamaGoodsUpdateOne {
	sguo.mutation.AddStockCount(i)
	return sguo
}

// SetStartDate sets the "start_date" field.
func (sguo *AdamaGoodsUpdateOne) SetStartDate(t time.Time) *AdamaGoodsUpdateOne {
	sguo.mutation.SetStartDate(t)
	return sguo
}

// SetEndDate sets the "end_date" field.
func (sguo *AdamaGoodsUpdateOne) SetEndDate(t time.Time) *AdamaGoodsUpdateOne {
	sguo.mutation.SetEndDate(t)
	return sguo
}

// Mutation returns the AdamaGoodsMutation object of the builder.
func (sguo *AdamaGoodsUpdateOne) Mutation() *AdamaGoodsMutation {
	return sguo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (sguo *AdamaGoodsUpdateOne) Select(field string, fields ...string) *AdamaGoodsUpdateOne {
	sguo.fields = append([]string{field}, fields...)
	return sguo
}

// Save executes the query and returns the updated AdamaGoods entity.
func (sguo *AdamaGoodsUpdateOne) Save(ctx context.Context) (*AdamaGoods, error) {
	var (
		err  error
		node *AdamaGoods
	)
	if len(sguo.hooks) == 0 {
		node, err = sguo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AdamaGoodsMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sguo.mutation = mutation
			node, err = sguo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(sguo.hooks) - 1; i >= 0; i-- {
			mut = sguo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sguo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (sguo *AdamaGoodsUpdateOne) SaveX(ctx context.Context) *AdamaGoods {
	node, err := sguo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (sguo *AdamaGoodsUpdateOne) Exec(ctx context.Context) error {
	_, err := sguo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sguo *AdamaGoodsUpdateOne) ExecX(ctx context.Context) {
	if err := sguo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (sguo *AdamaGoodsUpdateOne) sqlSave(ctx context.Context) (_node *AdamaGoods, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   adamagoods.Table,
			Columns: adamagoods.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: adamagoods.FieldID,
			},
		},
	}
	id, ok := sguo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing AdamaGoods.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := sguo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adamagoods.FieldID)
		for _, f := range fields {
			if !adamagoods.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != adamagoods.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := sguo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := sguo.mutation.GoodsID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: adamagoods.FieldGoodsID,
		})
	}
	if value, ok := sguo.mutation.AddedGoodsID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: adamagoods.FieldGoodsID,
		})
	}
	if value, ok := sguo.mutation.AdamaPrice(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: adamagoods.FieldAdamaPrice,
		})
	}
	if value, ok := sguo.mutation.AddedAdamaPrice(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: adamagoods.FieldAdamaPrice,
		})
	}
	if value, ok := sguo.mutation.StockCount(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: adamagoods.FieldStockCount,
		})
	}
	if value, ok := sguo.mutation.AddedStockCount(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: adamagoods.FieldStockCount,
		})
	}
	if value, ok := sguo.mutation.StartDate(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: adamagoods.FieldStartDate,
		})
	}
	if value, ok := sguo.mutation.EndDate(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: adamagoods.FieldEndDate,
		})
	}
	_node = &AdamaGoods{config: sguo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, sguo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adamagoods.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return _node, nil
}
