// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/littleSand/adama/app/order/service/internal/data/ent/adamaorder"
	"github.com/littleSand/adama/app/order/service/internal/data/ent/predicate"
)

// AdamaOrderDelete is the builder for deleting a AdamaOrder entity.
type AdamaOrderDelete struct {
	config
	hooks    []Hook
	mutation *AdamaOrderMutation
}

// Where adds a new predicate to the AdamaOrderDelete builder.
func (sod *AdamaOrderDelete) Where(ps ...predicate.AdamaOrder) *AdamaOrderDelete {
	sod.mutation.predicates = append(sod.mutation.predicates, ps...)
	return sod
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sod *AdamaOrderDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(sod.hooks) == 0 {
		affected, err = sod.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AdamaOrderMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sod.mutation = mutation
			affected, err = sod.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(sod.hooks) - 1; i >= 0; i-- {
			mut = sod.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sod.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (sod *AdamaOrderDelete) ExecX(ctx context.Context) int {
	n, err := sod.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sod *AdamaOrderDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: adamaorder.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: adamaorder.FieldID,
			},
		},
	}
	if ps := sod.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, sod.driver, _spec)
}

// AdamaOrderDeleteOne is the builder for deleting a single AdamaOrder entity.
type AdamaOrderDeleteOne struct {
	sod *AdamaOrderDelete
}

// Exec executes the deletion query.
func (sodo *AdamaOrderDeleteOne) Exec(ctx context.Context) error {
	n, err := sodo.sod.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{adamaorder.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sodo *AdamaOrderDeleteOne) ExecX(ctx context.Context) {
	sodo.sod.ExecX(ctx)
}
