// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/littleSand/adama/app/order/service/internal/data/ent/adamagoods"
	"github.com/littleSand/adama/app/order/service/internal/data/ent/predicate"
)

// AdamaGoodsQuery is the builder for querying AdamaGoods entities.
type AdamaGoodsQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.AdamaGoods
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AdamaGoodsQuery builder.
func (sgq *AdamaGoodsQuery) Where(ps ...predicate.AdamaGoods) *AdamaGoodsQuery {
	sgq.predicates = append(sgq.predicates, ps...)
	return sgq
}

// Limit adds a limit step to the query.
func (sgq *AdamaGoodsQuery) Limit(limit int) *AdamaGoodsQuery {
	sgq.limit = &limit
	return sgq
}

// Offset adds an offset step to the query.
func (sgq *AdamaGoodsQuery) Offset(offset int) *AdamaGoodsQuery {
	sgq.offset = &offset
	return sgq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sgq *AdamaGoodsQuery) Unique(unique bool) *AdamaGoodsQuery {
	sgq.unique = &unique
	return sgq
}

// Order adds an order step to the query.
func (sgq *AdamaGoodsQuery) Order(o ...OrderFunc) *AdamaGoodsQuery {
	sgq.order = append(sgq.order, o...)
	return sgq
}

// First returns the first AdamaGoods entity from the query.
// Returns a *NotFoundError when no AdamaGoods was found.
func (sgq *AdamaGoodsQuery) First(ctx context.Context) (*AdamaGoods, error) {
	nodes, err := sgq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{adamagoods.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sgq *AdamaGoodsQuery) FirstX(ctx context.Context) *AdamaGoods {
	node, err := sgq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AdamaGoods ID from the query.
// Returns a *NotFoundError when no AdamaGoods ID was found.
func (sgq *AdamaGoodsQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = sgq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{adamagoods.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sgq *AdamaGoodsQuery) FirstIDX(ctx context.Context) int64 {
	id, err := sgq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AdamaGoods entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one AdamaGoods entity is not found.
// Returns a *NotFoundError when no AdamaGoods entities are found.
func (sgq *AdamaGoodsQuery) Only(ctx context.Context) (*AdamaGoods, error) {
	nodes, err := sgq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{adamagoods.Label}
	default:
		return nil, &NotSingularError{adamagoods.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sgq *AdamaGoodsQuery) OnlyX(ctx context.Context) *AdamaGoods {
	node, err := sgq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AdamaGoods ID in the query.
// Returns a *NotSingularError when exactly one AdamaGoods ID is not found.
// Returns a *NotFoundError when no entities are found.
func (sgq *AdamaGoodsQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = sgq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{adamagoods.Label}
	default:
		err = &NotSingularError{adamagoods.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sgq *AdamaGoodsQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := sgq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AdamaGoodsSlice.
func (sgq *AdamaGoodsQuery) All(ctx context.Context) ([]*AdamaGoods, error) {
	if err := sgq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return sgq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (sgq *AdamaGoodsQuery) AllX(ctx context.Context) []*AdamaGoods {
	nodes, err := sgq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AdamaGoods IDs.
func (sgq *AdamaGoodsQuery) IDs(ctx context.Context) ([]int64, error) {
	var ids []int64
	if err := sgq.Select(adamagoods.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sgq *AdamaGoodsQuery) IDsX(ctx context.Context) []int64 {
	ids, err := sgq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sgq *AdamaGoodsQuery) Count(ctx context.Context) (int, error) {
	if err := sgq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return sgq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (sgq *AdamaGoodsQuery) CountX(ctx context.Context) int {
	count, err := sgq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sgq *AdamaGoodsQuery) Exist(ctx context.Context) (bool, error) {
	if err := sgq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return sgq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (sgq *AdamaGoodsQuery) ExistX(ctx context.Context) bool {
	exist, err := sgq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AdamaGoodsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sgq *AdamaGoodsQuery) Clone() *AdamaGoodsQuery {
	if sgq == nil {
		return nil
	}
	return &AdamaGoodsQuery{
		config:     sgq.config,
		limit:      sgq.limit,
		offset:     sgq.offset,
		order:      append([]OrderFunc{}, sgq.order...),
		predicates: append([]predicate.AdamaGoods{}, sgq.predicates...),
		// clone intermediate query.
		sql:  sgq.sql.Clone(),
		path: sgq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		GoodsID int64 `json:"goods_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AdamaGoods.Query().
//		GroupBy(adamagoods.FieldGoodsID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (sgq *AdamaGoodsQuery) GroupBy(field string, fields ...string) *AdamaGoodsGroupBy {
	group := &AdamaGoodsGroupBy{config: sgq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := sgq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return sgq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		GoodsID int64 `json:"goods_id,omitempty"`
//	}
//
//	client.AdamaGoods.Query().
//		Select(adamagoods.FieldGoodsID).
//		Scan(ctx, &v)
func (sgq *AdamaGoodsQuery) Select(field string, fields ...string) *AdamaGoodsSelect {
	sgq.fields = append([]string{field}, fields...)
	return &AdamaGoodsSelect{AdamaGoodsQuery: sgq}
}

func (sgq *AdamaGoodsQuery) prepareQuery(ctx context.Context) error {
	for _, f := range sgq.fields {
		if !adamagoods.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sgq.path != nil {
		prev, err := sgq.path(ctx)
		if err != nil {
			return err
		}
		sgq.sql = prev
	}
	return nil
}

func (sgq *AdamaGoodsQuery) sqlAll(ctx context.Context) ([]*AdamaGoods, error) {
	var (
		nodes = []*AdamaGoods{}
		_spec = sgq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &AdamaGoods{config: sgq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, sgq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (sgq *AdamaGoodsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sgq.querySpec()
	return sqlgraph.CountNodes(ctx, sgq.driver, _spec)
}

func (sgq *AdamaGoodsQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := sgq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (sgq *AdamaGoodsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   adamagoods.Table,
			Columns: adamagoods.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: adamagoods.FieldID,
			},
		},
		From:   sgq.sql,
		Unique: true,
	}
	if unique := sgq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := sgq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adamagoods.FieldID)
		for i := range fields {
			if fields[i] != adamagoods.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := sgq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sgq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sgq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sgq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sgq *AdamaGoodsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sgq.driver.Dialect())
	t1 := builder.Table(adamagoods.Table)
	selector := builder.Select(t1.Columns(adamagoods.Columns...)...).From(t1)
	if sgq.sql != nil {
		selector = sgq.sql
		selector.Select(selector.Columns(adamagoods.Columns...)...)
	}
	for _, p := range sgq.predicates {
		p(selector)
	}
	for _, p := range sgq.order {
		p(selector)
	}
	if offset := sgq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sgq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AdamaGoodsGroupBy is the group-by builder for AdamaGoods entities.
type AdamaGoodsGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sggb *AdamaGoodsGroupBy) Aggregate(fns ...AggregateFunc) *AdamaGoodsGroupBy {
	sggb.fns = append(sggb.fns, fns...)
	return sggb
}

// Scan applies the group-by query and scans the result into the given value.
func (sggb *AdamaGoodsGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := sggb.path(ctx)
	if err != nil {
		return err
	}
	sggb.sql = query
	return sggb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (sggb *AdamaGoodsGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := sggb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (sggb *AdamaGoodsGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(sggb.fields) > 1 {
		return nil, errors.New("ent: AdamaGoodsGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := sggb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (sggb *AdamaGoodsGroupBy) StringsX(ctx context.Context) []string {
	v, err := sggb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (sggb *AdamaGoodsGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = sggb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{adamagoods.Label}
	default:
		err = fmt.Errorf("ent: AdamaGoodsGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (sggb *AdamaGoodsGroupBy) StringX(ctx context.Context) string {
	v, err := sggb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (sggb *AdamaGoodsGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(sggb.fields) > 1 {
		return nil, errors.New("ent: AdamaGoodsGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := sggb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (sggb *AdamaGoodsGroupBy) IntsX(ctx context.Context) []int {
	v, err := sggb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (sggb *AdamaGoodsGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = sggb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{adamagoods.Label}
	default:
		err = fmt.Errorf("ent: AdamaGoodsGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (sggb *AdamaGoodsGroupBy) IntX(ctx context.Context) int {
	v, err := sggb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (sggb *AdamaGoodsGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(sggb.fields) > 1 {
		return nil, errors.New("ent: AdamaGoodsGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := sggb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (sggb *AdamaGoodsGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := sggb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (sggb *AdamaGoodsGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = sggb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{adamagoods.Label}
	default:
		err = fmt.Errorf("ent: AdamaGoodsGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (sggb *AdamaGoodsGroupBy) Float64X(ctx context.Context) float64 {
	v, err := sggb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (sggb *AdamaGoodsGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(sggb.fields) > 1 {
		return nil, errors.New("ent: AdamaGoodsGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := sggb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (sggb *AdamaGoodsGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := sggb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (sggb *AdamaGoodsGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = sggb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{adamagoods.Label}
	default:
		err = fmt.Errorf("ent: AdamaGoodsGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (sggb *AdamaGoodsGroupBy) BoolX(ctx context.Context) bool {
	v, err := sggb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (sggb *AdamaGoodsGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range sggb.fields {
		if !adamagoods.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := sggb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sggb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (sggb *AdamaGoodsGroupBy) sqlQuery() *sql.Selector {
	selector := sggb.sql
	columns := make([]string, 0, len(sggb.fields)+len(sggb.fns))
	columns = append(columns, sggb.fields...)
	for _, fn := range sggb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(sggb.fields...)
}

// AdamaGoodsSelect is the builder for selecting fields of AdamaGoods entities.
type AdamaGoodsSelect struct {
	*AdamaGoodsQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (sgs *AdamaGoodsSelect) Scan(ctx context.Context, v interface{}) error {
	if err := sgs.prepareQuery(ctx); err != nil {
		return err
	}
	sgs.sql = sgs.AdamaGoodsQuery.sqlQuery(ctx)
	return sgs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (sgs *AdamaGoodsSelect) ScanX(ctx context.Context, v interface{}) {
	if err := sgs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (sgs *AdamaGoodsSelect) Strings(ctx context.Context) ([]string, error) {
	if len(sgs.fields) > 1 {
		return nil, errors.New("ent: AdamaGoodsSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := sgs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (sgs *AdamaGoodsSelect) StringsX(ctx context.Context) []string {
	v, err := sgs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (sgs *AdamaGoodsSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = sgs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{adamagoods.Label}
	default:
		err = fmt.Errorf("ent: AdamaGoodsSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (sgs *AdamaGoodsSelect) StringX(ctx context.Context) string {
	v, err := sgs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (sgs *AdamaGoodsSelect) Ints(ctx context.Context) ([]int, error) {
	if len(sgs.fields) > 1 {
		return nil, errors.New("ent: AdamaGoodsSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := sgs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (sgs *AdamaGoodsSelect) IntsX(ctx context.Context) []int {
	v, err := sgs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (sgs *AdamaGoodsSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = sgs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{adamagoods.Label}
	default:
		err = fmt.Errorf("ent: AdamaGoodsSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (sgs *AdamaGoodsSelect) IntX(ctx context.Context) int {
	v, err := sgs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (sgs *AdamaGoodsSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(sgs.fields) > 1 {
		return nil, errors.New("ent: AdamaGoodsSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := sgs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (sgs *AdamaGoodsSelect) Float64sX(ctx context.Context) []float64 {
	v, err := sgs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (sgs *AdamaGoodsSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = sgs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{adamagoods.Label}
	default:
		err = fmt.Errorf("ent: AdamaGoodsSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (sgs *AdamaGoodsSelect) Float64X(ctx context.Context) float64 {
	v, err := sgs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (sgs *AdamaGoodsSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(sgs.fields) > 1 {
		return nil, errors.New("ent: AdamaGoodsSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := sgs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (sgs *AdamaGoodsSelect) BoolsX(ctx context.Context) []bool {
	v, err := sgs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (sgs *AdamaGoodsSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = sgs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{adamagoods.Label}
	default:
		err = fmt.Errorf("ent: AdamaGoodsSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (sgs *AdamaGoodsSelect) BoolX(ctx context.Context) bool {
	v, err := sgs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (sgs *AdamaGoodsSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := sgs.sqlQuery().Query()
	if err := sgs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (sgs *AdamaGoodsSelect) sqlQuery() sql.Querier {
	selector := sgs.sql
	selector.Select(selector.Columns(sgs.fields...)...)
	return selector
}
