// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/littleSand/adama/app/order/service/internal/data/ent/migrate"

	"github.com/littleSand/adama/app/order/service/internal/data/ent/adamagoods"
	"github.com/littleSand/adama/app/order/service/internal/data/ent/adamaorder"
	"github.com/littleSand/adama/app/order/service/internal/data/ent/order"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Order is the client for interacting with the Order builders.
	Order *OrderClient
	// AdamaGoods is the client for interacting with the AdamaGoods builders.
	AdamaGoods *AdamaGoodsClient
	// AdamaOrder is the client for interacting with the AdamaOrder builders.
	AdamaOrder *AdamaOrderClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Order = NewOrderClient(c.config)
	c.AdamaGoods = NewAdamaGoodsClient(c.config)
	c.AdamaOrder = NewAdamaOrderClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		Order:      NewOrderClient(cfg),
		AdamaGoods: NewAdamaGoodsClient(cfg),
		AdamaOrder: NewAdamaOrderClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		config:     cfg,
		Order:      NewOrderClient(cfg),
		AdamaGoods: NewAdamaGoodsClient(cfg),
		AdamaOrder: NewAdamaOrderClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Order.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Order.Use(hooks...)
	c.AdamaGoods.Use(hooks...)
	c.AdamaOrder.Use(hooks...)
}

// OrderClient is a client for the Order schema.
type OrderClient struct {
	config
}

// NewOrderClient returns a client for the Order from the given config.
func NewOrderClient(c config) *OrderClient {
	return &OrderClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `order.Hooks(f(g(h())))`.
func (c *OrderClient) Use(hooks ...Hook) {
	c.hooks.Order = append(c.hooks.Order, hooks...)
}

// Create returns a create builder for Order.
func (c *OrderClient) Create() *OrderCreate {
	mutation := newOrderMutation(c.config, OpCreate)
	return &OrderCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Order entities.
func (c *OrderClient) CreateBulk(builders ...*OrderCreate) *OrderCreateBulk {
	return &OrderCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Order.
func (c *OrderClient) Update() *OrderUpdate {
	mutation := newOrderMutation(c.config, OpUpdate)
	return &OrderUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OrderClient) UpdateOne(o *Order) *OrderUpdateOne {
	mutation := newOrderMutation(c.config, OpUpdateOne, withOrder(o))
	return &OrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OrderClient) UpdateOneID(id int64) *OrderUpdateOne {
	mutation := newOrderMutation(c.config, OpUpdateOne, withOrderID(id))
	return &OrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Order.
func (c *OrderClient) Delete() *OrderDelete {
	mutation := newOrderMutation(c.config, OpDelete)
	return &OrderDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *OrderClient) DeleteOne(o *Order) *OrderDeleteOne {
	return c.DeleteOneID(o.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *OrderClient) DeleteOneID(id int64) *OrderDeleteOne {
	builder := c.Delete().Where(order.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OrderDeleteOne{builder}
}

// Query returns a query builder for Order.
func (c *OrderClient) Query() *OrderQuery {
	return &OrderQuery{
		config: c.config,
	}
}

// Get returns a Order entity by its id.
func (c *OrderClient) Get(ctx context.Context, id int64) (*Order, error) {
	return c.Query().Where(order.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OrderClient) GetX(ctx context.Context, id int64) *Order {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *OrderClient) Hooks() []Hook {
	return c.hooks.Order
}

// AdamaGoodsClient is a client for the AdamaGoods schema.
type AdamaGoodsClient struct {
	config
}

// NewAdamaGoodsClient returns a client for the AdamaGoods from the given config.
func NewAdamaGoodsClient(c config) *AdamaGoodsClient {
	return &AdamaGoodsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `adamagoods.Hooks(f(g(h())))`.
func (c *AdamaGoodsClient) Use(hooks ...Hook) {
	c.hooks.AdamaGoods = append(c.hooks.AdamaGoods, hooks...)
}

// Create returns a create builder for AdamaGoods.
func (c *AdamaGoodsClient) Create() *AdamaGoodsCreate {
	mutation := newAdamaGoodsMutation(c.config, OpCreate)
	return &AdamaGoodsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AdamaGoods entities.
func (c *AdamaGoodsClient) CreateBulk(builders ...*AdamaGoodsCreate) *AdamaGoodsCreateBulk {
	return &AdamaGoodsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AdamaGoods.
func (c *AdamaGoodsClient) Update() *AdamaGoodsUpdate {
	mutation := newAdamaGoodsMutation(c.config, OpUpdate)
	return &AdamaGoodsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AdamaGoodsClient) UpdateOne(sg *AdamaGoods) *AdamaGoodsUpdateOne {
	mutation := newAdamaGoodsMutation(c.config, OpUpdateOne, withAdamaGoods(sg))
	return &AdamaGoodsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AdamaGoodsClient) UpdateOneID(id int64) *AdamaGoodsUpdateOne {
	mutation := newAdamaGoodsMutation(c.config, OpUpdateOne, withAdamaGoodsID(id))
	return &AdamaGoodsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AdamaGoods.
func (c *AdamaGoodsClient) Delete() *AdamaGoodsDelete {
	mutation := newAdamaGoodsMutation(c.config, OpDelete)
	return &AdamaGoodsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *AdamaGoodsClient) DeleteOne(sg *AdamaGoods) *AdamaGoodsDeleteOne {
	return c.DeleteOneID(sg.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *AdamaGoodsClient) DeleteOneID(id int64) *AdamaGoodsDeleteOne {
	builder := c.Delete().Where(adamagoods.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AdamaGoodsDeleteOne{builder}
}

// Query returns a query builder for AdamaGoods.
func (c *AdamaGoodsClient) Query() *AdamaGoodsQuery {
	return &AdamaGoodsQuery{
		config: c.config,
	}
}

// Get returns a AdamaGoods entity by its id.
func (c *AdamaGoodsClient) Get(ctx context.Context, id int64) (*AdamaGoods, error) {
	return c.Query().Where(adamagoods.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AdamaGoodsClient) GetX(ctx context.Context, id int64) *AdamaGoods {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AdamaGoodsClient) Hooks() []Hook {
	return c.hooks.AdamaGoods
}

// AdamaOrderClient is a client for the AdamaOrder schema.
type AdamaOrderClient struct {
	config
}

// NewAdamaOrderClient returns a client for the AdamaOrder from the given config.
func NewAdamaOrderClient(c config) *AdamaOrderClient {
	return &AdamaOrderClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `adamaorder.Hooks(f(g(h())))`.
func (c *AdamaOrderClient) Use(hooks ...Hook) {
	c.hooks.AdamaOrder = append(c.hooks.AdamaOrder, hooks...)
}

// Create returns a create builder for AdamaOrder.
func (c *AdamaOrderClient) Create() *AdamaOrderCreate {
	mutation := newAdamaOrderMutation(c.config, OpCreate)
	return &AdamaOrderCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AdamaOrder entities.
func (c *AdamaOrderClient) CreateBulk(builders ...*AdamaOrderCreate) *AdamaOrderCreateBulk {
	return &AdamaOrderCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AdamaOrder.
func (c *AdamaOrderClient) Update() *AdamaOrderUpdate {
	mutation := newAdamaOrderMutation(c.config, OpUpdate)
	return &AdamaOrderUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AdamaOrderClient) UpdateOne(so *AdamaOrder) *AdamaOrderUpdateOne {
	mutation := newAdamaOrderMutation(c.config, OpUpdateOne, withAdamaOrder(so))
	return &AdamaOrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AdamaOrderClient) UpdateOneID(id int64) *AdamaOrderUpdateOne {
	mutation := newAdamaOrderMutation(c.config, OpUpdateOne, withAdamaOrderID(id))
	return &AdamaOrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AdamaOrder.
func (c *AdamaOrderClient) Delete() *AdamaOrderDelete {
	mutation := newAdamaOrderMutation(c.config, OpDelete)
	return &AdamaOrderDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *AdamaOrderClient) DeleteOne(so *AdamaOrder) *AdamaOrderDeleteOne {
	return c.DeleteOneID(so.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *AdamaOrderClient) DeleteOneID(id int64) *AdamaOrderDeleteOne {
	builder := c.Delete().Where(adamaorder.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AdamaOrderDeleteOne{builder}
}

// Query returns a query builder for AdamaOrder.
func (c *AdamaOrderClient) Query() *AdamaOrderQuery {
	return &AdamaOrderQuery{
		config: c.config,
	}
}

// Get returns a AdamaOrder entity by its id.
func (c *AdamaOrderClient) Get(ctx context.Context, id int64) (*AdamaOrder, error) {
	return c.Query().Where(adamaorder.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AdamaOrderClient) GetX(ctx context.Context, id int64) *AdamaOrder {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AdamaOrderClient) Hooks() []Hook {
	return c.hooks.AdamaOrder
}
