// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"sync"
	"time"

	"github.com/littleSand/adama/app/order/service/internal/data/ent/adamagoods"
	"github.com/littleSand/adama/app/order/service/internal/data/ent/adamaorder"
	"github.com/littleSand/adama/app/order/service/internal/data/ent/order"
	"github.com/littleSand/adama/app/order/service/internal/data/ent/predicate"

	"entgo.io/ent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeOrder      = "Order"
	TypeAdamaGoods = "AdamaGoods"
	TypeAdamaOrder = "AdamaOrder"
)

// OrderMutation represents an operation that mutates the Order nodes in the graph.
type OrderMutation struct {
	config
	op            Op
	typ           string
	id            *int64
	sn            *string
	gid           *int64
	addgid        *int64
	uid           *int64
	adduid        *int64
	created_at    *time.Time
	updated_at    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Order, error)
	predicates    []predicate.Order
}

var _ ent.Mutation = (*OrderMutation)(nil)

// orderOption allows management of the mutation configuration using functional options.
type orderOption func(*OrderMutation)

// newOrderMutation creates new mutation for the Order entity.
func newOrderMutation(c config, op Op, opts ...orderOption) *OrderMutation {
	m := &OrderMutation{
		config:        c,
		op:            op,
		typ:           TypeOrder,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withOrderID sets the ID field of the mutation.
func withOrderID(id int64) orderOption {
	return func(m *OrderMutation) {
		var (
			err   error
			once  sync.Once
			value *Order
		)
		m.oldValue = func(ctx context.Context) (*Order, error) {
			once.Do(func() {
				if m.done {
					err = fmt.Errorf("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Order.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withOrder sets the old Order of the mutation.
func withOrder(node *Order) orderOption {
	return func(m *OrderMutation) {
		m.oldValue = func(context.Context) (*Order, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m OrderMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m OrderMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Order entities.
func (m *OrderMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID
// is only available if it was provided to the builder.
func (m *OrderMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetSn sets the "sn" field.
func (m *OrderMutation) SetSn(s string) {
	m.sn = &s
}

// Sn returns the value of the "sn" field in the mutation.
func (m *OrderMutation) Sn() (r string, exists bool) {
	v := m.sn
	if v == nil {
		return
	}
	return *v, true
}

// OldSn returns the old "sn" field's value of the Order entity.
// If the Order object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OrderMutation) OldSn(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldSn is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldSn requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSn: %w", err)
	}
	return oldValue.Sn, nil
}

// ResetSn resets all changes to the "sn" field.
func (m *OrderMutation) ResetSn() {
	m.sn = nil
}

// SetGid sets the "gid" field.
func (m *OrderMutation) SetGid(i int64) {
	m.gid = &i
	m.addgid = nil
}

// Gid returns the value of the "gid" field in the mutation.
func (m *OrderMutation) Gid() (r int64, exists bool) {
	v := m.gid
	if v == nil {
		return
	}
	return *v, true
}

// OldGid returns the old "gid" field's value of the Order entity.
// If the Order object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OrderMutation) OldGid(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldGid is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldGid requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGid: %w", err)
	}
	return oldValue.Gid, nil
}

// AddGid adds i to the "gid" field.
func (m *OrderMutation) AddGid(i int64) {
	if m.addgid != nil {
		*m.addgid += i
	} else {
		m.addgid = &i
	}
}

// AddedGid returns the value that was added to the "gid" field in this mutation.
func (m *OrderMutation) AddedGid() (r int64, exists bool) {
	v := m.addgid
	if v == nil {
		return
	}
	return *v, true
}

// ResetGid resets all changes to the "gid" field.
func (m *OrderMutation) ResetGid() {
	m.gid = nil
	m.addgid = nil
}

// SetUID sets the "uid" field.
func (m *OrderMutation) SetUID(i int64) {
	m.uid = &i
	m.adduid = nil
}

// UID returns the value of the "uid" field in the mutation.
func (m *OrderMutation) UID() (r int64, exists bool) {
	v := m.uid
	if v == nil {
		return
	}
	return *v, true
}

// OldUID returns the old "uid" field's value of the Order entity.
// If the Order object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OrderMutation) OldUID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldUID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldUID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUID: %w", err)
	}
	return oldValue.UID, nil
}

// AddUID adds i to the "uid" field.
func (m *OrderMutation) AddUID(i int64) {
	if m.adduid != nil {
		*m.adduid += i
	} else {
		m.adduid = &i
	}
}

// AddedUID returns the value that was added to the "uid" field in this mutation.
func (m *OrderMutation) AddedUID() (r int64, exists bool) {
	v := m.adduid
	if v == nil {
		return
	}
	return *v, true
}

// ResetUID resets all changes to the "uid" field.
func (m *OrderMutation) ResetUID() {
	m.uid = nil
	m.adduid = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *OrderMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *OrderMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Order entity.
// If the Order object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OrderMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *OrderMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *OrderMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *OrderMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Order entity.
// If the Order object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OrderMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *OrderMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// Op returns the operation name.
func (m *OrderMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Order).
func (m *OrderMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *OrderMutation) Fields() []string {
	fields := make([]string, 0, 5)
	if m.sn != nil {
		fields = append(fields, order.FieldSn)
	}
	if m.gid != nil {
		fields = append(fields, order.FieldGid)
	}
	if m.uid != nil {
		fields = append(fields, order.FieldUID)
	}
	if m.created_at != nil {
		fields = append(fields, order.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, order.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *OrderMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case order.FieldSn:
		return m.Sn()
	case order.FieldGid:
		return m.Gid()
	case order.FieldUID:
		return m.UID()
	case order.FieldCreatedAt:
		return m.CreatedAt()
	case order.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *OrderMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case order.FieldSn:
		return m.OldSn(ctx)
	case order.FieldGid:
		return m.OldGid(ctx)
	case order.FieldUID:
		return m.OldUID(ctx)
	case order.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case order.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Order field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *OrderMutation) SetField(name string, value ent.Value) error {
	switch name {
	case order.FieldSn:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSn(v)
		return nil
	case order.FieldGid:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGid(v)
		return nil
	case order.FieldUID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUID(v)
		return nil
	case order.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case order.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Order field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *OrderMutation) AddedFields() []string {
	var fields []string
	if m.addgid != nil {
		fields = append(fields, order.FieldGid)
	}
	if m.adduid != nil {
		fields = append(fields, order.FieldUID)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *OrderMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case order.FieldGid:
		return m.AddedGid()
	case order.FieldUID:
		return m.AddedUID()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *OrderMutation) AddField(name string, value ent.Value) error {
	switch name {
	case order.FieldGid:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddGid(v)
		return nil
	case order.FieldUID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddUID(v)
		return nil
	}
	return fmt.Errorf("unknown Order numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *OrderMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *OrderMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *OrderMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Order nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *OrderMutation) ResetField(name string) error {
	switch name {
	case order.FieldSn:
		m.ResetSn()
		return nil
	case order.FieldGid:
		m.ResetGid()
		return nil
	case order.FieldUID:
		m.ResetUID()
		return nil
	case order.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case order.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown Order field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *OrderMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *OrderMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *OrderMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *OrderMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *OrderMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *OrderMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *OrderMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Order unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *OrderMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Order edge %s", name)
}

// AdamaGoodsMutation represents an operation that mutates the AdamaGoods nodes in the graph.
type AdamaGoodsMutation struct {
	config
	op             Op
	typ            string
	id             *int64
	goods_id       *int64
	addgoods_id    *int64
	adama_price    *float64
	addadama_price *float64
	stock_count    *int64
	addstock_count *int64
	start_date     *time.Time
	end_date       *time.Time
	clearedFields  map[string]struct{}
	done           bool
	oldValue       func(context.Context) (*AdamaGoods, error)
	predicates     []predicate.AdamaGoods
}

var _ ent.Mutation = (*AdamaGoodsMutation)(nil)

// adamagoodsOption allows management of the mutation configuration using functional options.
type adamagoodsOption func(*AdamaGoodsMutation)

// newAdamaGoodsMutation creates new mutation for the AdamaGoods entity.
func newAdamaGoodsMutation(c config, op Op, opts ...adamagoodsOption) *AdamaGoodsMutation {
	m := &AdamaGoodsMutation{
		config:        c,
		op:            op,
		typ:           TypeAdamaGoods,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withAdamaGoodsID sets the ID field of the mutation.
func withAdamaGoodsID(id int64) adamagoodsOption {
	return func(m *AdamaGoodsMutation) {
		var (
			err   error
			once  sync.Once
			value *AdamaGoods
		)
		m.oldValue = func(ctx context.Context) (*AdamaGoods, error) {
			once.Do(func() {
				if m.done {
					err = fmt.Errorf("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().AdamaGoods.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withAdamaGoods sets the old AdamaGoods of the mutation.
func withAdamaGoods(node *AdamaGoods) adamagoodsOption {
	return func(m *AdamaGoodsMutation) {
		m.oldValue = func(context.Context) (*AdamaGoods, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m AdamaGoodsMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m AdamaGoodsMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of AdamaGoods entities.
func (m *AdamaGoodsMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID
// is only available if it was provided to the builder.
func (m *AdamaGoodsMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetGoodsID sets the "goods_id" field.
func (m *AdamaGoodsMutation) SetGoodsID(i int64) {
	m.goods_id = &i
	m.addgoods_id = nil
}

// GoodsID returns the value of the "goods_id" field in the mutation.
func (m *AdamaGoodsMutation) GoodsID() (r int64, exists bool) {
	v := m.goods_id
	if v == nil {
		return
	}
	return *v, true
}

// OldGoodsID returns the old "goods_id" field's value of the AdamaGoods entity.
// If the AdamaGoods object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AdamaGoodsMutation) OldGoodsID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldGoodsID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldGoodsID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGoodsID: %w", err)
	}
	return oldValue.GoodsID, nil
}

// AddGoodsID adds i to the "goods_id" field.
func (m *AdamaGoodsMutation) AddGoodsID(i int64) {
	if m.addgoods_id != nil {
		*m.addgoods_id += i
	} else {
		m.addgoods_id = &i
	}
}

// AddedGoodsID returns the value that was added to the "goods_id" field in this mutation.
func (m *AdamaGoodsMutation) AddedGoodsID() (r int64, exists bool) {
	v := m.addgoods_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetGoodsID resets all changes to the "goods_id" field.
func (m *AdamaGoodsMutation) ResetGoodsID() {
	m.goods_id = nil
	m.addgoods_id = nil
}

// SetAdamaPrice sets the "adama_price" field.
func (m *AdamaGoodsMutation) SetAdamaPrice(f float64) {
	m.adama_price = &f
	m.addadama_price = nil
}

// AdamaPrice returns the value of the "adama_price" field in the mutation.
func (m *AdamaGoodsMutation) AdamaPrice() (r float64, exists bool) {
	v := m.adama_price
	if v == nil {
		return
	}
	return *v, true
}

// OldAdamaPrice returns the old "adama_price" field's value of the AdamaGoods entity.
// If the AdamaGoods object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AdamaGoodsMutation) OldAdamaPrice(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldAdamaPrice is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldAdamaPrice requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAdamaPrice: %w", err)
	}
	return oldValue.AdamaPrice, nil
}

// AddAdamaPrice adds f to the "adama_price" field.
func (m *AdamaGoodsMutation) AddAdamaPrice(f float64) {
	if m.addadama_price != nil {
		*m.addadama_price += f
	} else {
		m.addadama_price = &f
	}
}

// AddedAdamaPrice returns the value that was added to the "adama_price" field in this mutation.
func (m *AdamaGoodsMutation) AddedAdamaPrice() (r float64, exists bool) {
	v := m.addadama_price
	if v == nil {
		return
	}
	return *v, true
}

// ResetAdamaPrice resets all changes to the "adama_price" field.
func (m *AdamaGoodsMutation) ResetAdamaPrice() {
	m.adama_price = nil
	m.addadama_price = nil
}

// SetStockCount sets the "stock_count" field.
func (m *AdamaGoodsMutation) SetStockCount(i int64) {
	m.stock_count = &i
	m.addstock_count = nil
}

// StockCount returns the value of the "stock_count" field in the mutation.
func (m *AdamaGoodsMutation) StockCount() (r int64, exists bool) {
	v := m.stock_count
	if v == nil {
		return
	}
	return *v, true
}

// OldStockCount returns the old "stock_count" field's value of the AdamaGoods entity.
// If the AdamaGoods object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AdamaGoodsMutation) OldStockCount(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldStockCount is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldStockCount requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStockCount: %w", err)
	}
	return oldValue.StockCount, nil
}

// AddStockCount adds i to the "stock_count" field.
func (m *AdamaGoodsMutation) AddStockCount(i int64) {
	if m.addstock_count != nil {
		*m.addstock_count += i
	} else {
		m.addstock_count = &i
	}
}

// AddedStockCount returns the value that was added to the "stock_count" field in this mutation.
func (m *AdamaGoodsMutation) AddedStockCount() (r int64, exists bool) {
	v := m.addstock_count
	if v == nil {
		return
	}
	return *v, true
}

// ResetStockCount resets all changes to the "stock_count" field.
func (m *AdamaGoodsMutation) ResetStockCount() {
	m.stock_count = nil
	m.addstock_count = nil
}

// SetStartDate sets the "start_date" field.
func (m *AdamaGoodsMutation) SetStartDate(t time.Time) {
	m.start_date = &t
}

// StartDate returns the value of the "start_date" field in the mutation.
func (m *AdamaGoodsMutation) StartDate() (r time.Time, exists bool) {
	v := m.start_date
	if v == nil {
		return
	}
	return *v, true
}

// OldStartDate returns the old "start_date" field's value of the AdamaGoods entity.
// If the AdamaGoods object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AdamaGoodsMutation) OldStartDate(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldStartDate is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldStartDate requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStartDate: %w", err)
	}
	return oldValue.StartDate, nil
}

// ResetStartDate resets all changes to the "start_date" field.
func (m *AdamaGoodsMutation) ResetStartDate() {
	m.start_date = nil
}

// SetEndDate sets the "end_date" field.
func (m *AdamaGoodsMutation) SetEndDate(t time.Time) {
	m.end_date = &t
}

// EndDate returns the value of the "end_date" field in the mutation.
func (m *AdamaGoodsMutation) EndDate() (r time.Time, exists bool) {
	v := m.end_date
	if v == nil {
		return
	}
	return *v, true
}

// OldEndDate returns the old "end_date" field's value of the AdamaGoods entity.
// If the AdamaGoods object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AdamaGoodsMutation) OldEndDate(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldEndDate is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldEndDate requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEndDate: %w", err)
	}
	return oldValue.EndDate, nil
}

// ResetEndDate resets all changes to the "end_date" field.
func (m *AdamaGoodsMutation) ResetEndDate() {
	m.end_date = nil
}

// Op returns the operation name.
func (m *AdamaGoodsMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (AdamaGoods).
func (m *AdamaGoodsMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *AdamaGoodsMutation) Fields() []string {
	fields := make([]string, 0, 5)
	if m.goods_id != nil {
		fields = append(fields, adamagoods.FieldGoodsID)
	}
	if m.adama_price != nil {
		fields = append(fields, adamagoods.FieldAdamaPrice)
	}
	if m.stock_count != nil {
		fields = append(fields, adamagoods.FieldStockCount)
	}
	if m.start_date != nil {
		fields = append(fields, adamagoods.FieldStartDate)
	}
	if m.end_date != nil {
		fields = append(fields, adamagoods.FieldEndDate)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *AdamaGoodsMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case adamagoods.FieldGoodsID:
		return m.GoodsID()
	case adamagoods.FieldAdamaPrice:
		return m.AdamaPrice()
	case adamagoods.FieldStockCount:
		return m.StockCount()
	case adamagoods.FieldStartDate:
		return m.StartDate()
	case adamagoods.FieldEndDate:
		return m.EndDate()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *AdamaGoodsMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case adamagoods.FieldGoodsID:
		return m.OldGoodsID(ctx)
	case adamagoods.FieldAdamaPrice:
		return m.OldAdamaPrice(ctx)
	case adamagoods.FieldStockCount:
		return m.OldStockCount(ctx)
	case adamagoods.FieldStartDate:
		return m.OldStartDate(ctx)
	case adamagoods.FieldEndDate:
		return m.OldEndDate(ctx)
	}
	return nil, fmt.Errorf("unknown AdamaGoods field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AdamaGoodsMutation) SetField(name string, value ent.Value) error {
	switch name {
	case adamagoods.FieldGoodsID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGoodsID(v)
		return nil
	case adamagoods.FieldAdamaPrice:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAdamaPrice(v)
		return nil
	case adamagoods.FieldStockCount:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStockCount(v)
		return nil
	case adamagoods.FieldStartDate:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStartDate(v)
		return nil
	case adamagoods.FieldEndDate:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEndDate(v)
		return nil
	}
	return fmt.Errorf("unknown AdamaGoods field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *AdamaGoodsMutation) AddedFields() []string {
	var fields []string
	if m.addgoods_id != nil {
		fields = append(fields, adamagoods.FieldGoodsID)
	}
	if m.addadama_price != nil {
		fields = append(fields, adamagoods.FieldAdamaPrice)
	}
	if m.addstock_count != nil {
		fields = append(fields, adamagoods.FieldStockCount)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *AdamaGoodsMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case adamagoods.FieldGoodsID:
		return m.AddedGoodsID()
	case adamagoods.FieldAdamaPrice:
		return m.AddedAdamaPrice()
	case adamagoods.FieldStockCount:
		return m.AddedStockCount()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AdamaGoodsMutation) AddField(name string, value ent.Value) error {
	switch name {
	case adamagoods.FieldGoodsID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddGoodsID(v)
		return nil
	case adamagoods.FieldAdamaPrice:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddAdamaPrice(v)
		return nil
	case adamagoods.FieldStockCount:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddStockCount(v)
		return nil
	}
	return fmt.Errorf("unknown AdamaGoods numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *AdamaGoodsMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *AdamaGoodsMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *AdamaGoodsMutation) ClearField(name string) error {
	return fmt.Errorf("unknown AdamaGoods nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *AdamaGoodsMutation) ResetField(name string) error {
	switch name {
	case adamagoods.FieldGoodsID:
		m.ResetGoodsID()
		return nil
	case adamagoods.FieldAdamaPrice:
		m.ResetAdamaPrice()
		return nil
	case adamagoods.FieldStockCount:
		m.ResetStockCount()
		return nil
	case adamagoods.FieldStartDate:
		m.ResetStartDate()
		return nil
	case adamagoods.FieldEndDate:
		m.ResetEndDate()
		return nil
	}
	return fmt.Errorf("unknown AdamaGoods field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *AdamaGoodsMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *AdamaGoodsMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *AdamaGoodsMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *AdamaGoodsMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *AdamaGoodsMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *AdamaGoodsMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *AdamaGoodsMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown AdamaGoods unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *AdamaGoodsMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown AdamaGoods edge %s", name)
}

// AdamaOrderMutation represents an operation that mutates the AdamaOrder nodes in the graph.
type AdamaOrderMutation struct {
	config
	op            Op
	typ           string
	id            *int64
	user_id       *int64
	adduser_id    *int64
	order_id      *int64
	addorder_id   *int64
	goods_id      *int64
	addgoods_id   *int64
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*AdamaOrder, error)
	predicates    []predicate.AdamaOrder
}

var _ ent.Mutation = (*AdamaOrderMutation)(nil)

// adamaorderOption allows management of the mutation configuration using functional options.
type adamaorderOption func(*AdamaOrderMutation)

// newAdamaOrderMutation creates new mutation for the AdamaOrder entity.
func newAdamaOrderMutation(c config, op Op, opts ...adamaorderOption) *AdamaOrderMutation {
	m := &AdamaOrderMutation{
		config:        c,
		op:            op,
		typ:           TypeAdamaOrder,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withAdamaOrderID sets the ID field of the mutation.
func withAdamaOrderID(id int64) adamaorderOption {
	return func(m *AdamaOrderMutation) {
		var (
			err   error
			once  sync.Once
			value *AdamaOrder
		)
		m.oldValue = func(ctx context.Context) (*AdamaOrder, error) {
			once.Do(func() {
				if m.done {
					err = fmt.Errorf("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().AdamaOrder.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withAdamaOrder sets the old AdamaOrder of the mutation.
func withAdamaOrder(node *AdamaOrder) adamaorderOption {
	return func(m *AdamaOrderMutation) {
		m.oldValue = func(context.Context) (*AdamaOrder, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m AdamaOrderMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m AdamaOrderMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of AdamaOrder entities.
func (m *AdamaOrderMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID
// is only available if it was provided to the builder.
func (m *AdamaOrderMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetUserID sets the "user_id" field.
func (m *AdamaOrderMutation) SetUserID(i int64) {
	m.user_id = &i
	m.adduser_id = nil
}

// UserID returns the value of the "user_id" field in the mutation.
func (m *AdamaOrderMutation) UserID() (r int64, exists bool) {
	v := m.user_id
	if v == nil {
		return
	}
	return *v, true
}

// OldUserID returns the old "user_id" field's value of the AdamaOrder entity.
// If the AdamaOrder object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AdamaOrderMutation) OldUserID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldUserID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldUserID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserID: %w", err)
	}
	return oldValue.UserID, nil
}

// AddUserID adds i to the "user_id" field.
func (m *AdamaOrderMutation) AddUserID(i int64) {
	if m.adduser_id != nil {
		*m.adduser_id += i
	} else {
		m.adduser_id = &i
	}
}

// AddedUserID returns the value that was added to the "user_id" field in this mutation.
func (m *AdamaOrderMutation) AddedUserID() (r int64, exists bool) {
	v := m.adduser_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetUserID resets all changes to the "user_id" field.
func (m *AdamaOrderMutation) ResetUserID() {
	m.user_id = nil
	m.adduser_id = nil
}

// SetOrderID sets the "order_id" field.
func (m *AdamaOrderMutation) SetOrderID(i int64) {
	m.order_id = &i
	m.addorder_id = nil
}

// OrderID returns the value of the "order_id" field in the mutation.
func (m *AdamaOrderMutation) OrderID() (r int64, exists bool) {
	v := m.order_id
	if v == nil {
		return
	}
	return *v, true
}

// OldOrderID returns the old "order_id" field's value of the AdamaOrder entity.
// If the AdamaOrder object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AdamaOrderMutation) OldOrderID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldOrderID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldOrderID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOrderID: %w", err)
	}
	return oldValue.OrderID, nil
}

// AddOrderID adds i to the "order_id" field.
func (m *AdamaOrderMutation) AddOrderID(i int64) {
	if m.addorder_id != nil {
		*m.addorder_id += i
	} else {
		m.addorder_id = &i
	}
}

// AddedOrderID returns the value that was added to the "order_id" field in this mutation.
func (m *AdamaOrderMutation) AddedOrderID() (r int64, exists bool) {
	v := m.addorder_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetOrderID resets all changes to the "order_id" field.
func (m *AdamaOrderMutation) ResetOrderID() {
	m.order_id = nil
	m.addorder_id = nil
}

// SetGoodsID sets the "goods_id" field.
func (m *AdamaOrderMutation) SetGoodsID(i int64) {
	m.goods_id = &i
	m.addgoods_id = nil
}

// GoodsID returns the value of the "goods_id" field in the mutation.
func (m *AdamaOrderMutation) GoodsID() (r int64, exists bool) {
	v := m.goods_id
	if v == nil {
		return
	}
	return *v, true
}

// OldGoodsID returns the old "goods_id" field's value of the AdamaOrder entity.
// If the AdamaOrder object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AdamaOrderMutation) OldGoodsID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldGoodsID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldGoodsID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGoodsID: %w", err)
	}
	return oldValue.GoodsID, nil
}

// AddGoodsID adds i to the "goods_id" field.
func (m *AdamaOrderMutation) AddGoodsID(i int64) {
	if m.addgoods_id != nil {
		*m.addgoods_id += i
	} else {
		m.addgoods_id = &i
	}
}

// AddedGoodsID returns the value that was added to the "goods_id" field in this mutation.
func (m *AdamaOrderMutation) AddedGoodsID() (r int64, exists bool) {
	v := m.addgoods_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetGoodsID resets all changes to the "goods_id" field.
func (m *AdamaOrderMutation) ResetGoodsID() {
	m.goods_id = nil
	m.addgoods_id = nil
}

// Op returns the operation name.
func (m *AdamaOrderMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (AdamaOrder).
func (m *AdamaOrderMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *AdamaOrderMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.user_id != nil {
		fields = append(fields, adamaorder.FieldUserID)
	}
	if m.order_id != nil {
		fields = append(fields, adamaorder.FieldOrderID)
	}
	if m.goods_id != nil {
		fields = append(fields, adamaorder.FieldGoodsID)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *AdamaOrderMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case adamaorder.FieldUserID:
		return m.UserID()
	case adamaorder.FieldOrderID:
		return m.OrderID()
	case adamaorder.FieldGoodsID:
		return m.GoodsID()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *AdamaOrderMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case adamaorder.FieldUserID:
		return m.OldUserID(ctx)
	case adamaorder.FieldOrderID:
		return m.OldOrderID(ctx)
	case adamaorder.FieldGoodsID:
		return m.OldGoodsID(ctx)
	}
	return nil, fmt.Errorf("unknown AdamaOrder field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AdamaOrderMutation) SetField(name string, value ent.Value) error {
	switch name {
	case adamaorder.FieldUserID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserID(v)
		return nil
	case adamaorder.FieldOrderID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOrderID(v)
		return nil
	case adamaorder.FieldGoodsID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGoodsID(v)
		return nil
	}
	return fmt.Errorf("unknown AdamaOrder field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *AdamaOrderMutation) AddedFields() []string {
	var fields []string
	if m.adduser_id != nil {
		fields = append(fields, adamaorder.FieldUserID)
	}
	if m.addorder_id != nil {
		fields = append(fields, adamaorder.FieldOrderID)
	}
	if m.addgoods_id != nil {
		fields = append(fields, adamaorder.FieldGoodsID)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *AdamaOrderMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case adamaorder.FieldUserID:
		return m.AddedUserID()
	case adamaorder.FieldOrderID:
		return m.AddedOrderID()
	case adamaorder.FieldGoodsID:
		return m.AddedGoodsID()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AdamaOrderMutation) AddField(name string, value ent.Value) error {
	switch name {
	case adamaorder.FieldUserID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddUserID(v)
		return nil
	case adamaorder.FieldOrderID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddOrderID(v)
		return nil
	case adamaorder.FieldGoodsID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddGoodsID(v)
		return nil
	}
	return fmt.Errorf("unknown AdamaOrder numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *AdamaOrderMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *AdamaOrderMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *AdamaOrderMutation) ClearField(name string) error {
	return fmt.Errorf("unknown AdamaOrder nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *AdamaOrderMutation) ResetField(name string) error {
	switch name {
	case adamaorder.FieldUserID:
		m.ResetUserID()
		return nil
	case adamaorder.FieldOrderID:
		m.ResetOrderID()
		return nil
	case adamaorder.FieldGoodsID:
		m.ResetGoodsID()
		return nil
	}
	return fmt.Errorf("unknown AdamaOrder field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *AdamaOrderMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *AdamaOrderMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *AdamaOrderMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *AdamaOrderMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *AdamaOrderMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *AdamaOrderMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *AdamaOrderMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown AdamaOrder unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *AdamaOrderMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown AdamaOrder edge %s", name)
}
